gui:
  language: "en"
  nerdFontsVersion: "3"
  showAllContainers: false
  border: "single"
  returnImmediately: false
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - default
logs:
  since: ""
