gui:
  language: "en"
  nerdFontsVersion: "3"
  showAllContainers: false
  border: "hidden"
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - default
quitOnTopLevelReturn: true
