gui:
  language: "en"
  nerdFontsVersion: "3"
  showAllContainers: false
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - default
quitOnTopLevelReturn: true
keybinding:
  universal:
    quit: "<esc>"
    return: "q"
