return {
  -- 'nvim-telescope/telescope.nvim',
  -- tag = '0.1.5',
  -- lazy = false,
  -- dependencies = {
  --   'nvim-lua/plenary.nvim',
  --   { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
  --   'nvim-telescope/telescope-file-browser.nvim',
  --   "nvim-tree/nvim-web-devicons",
  -- },
  -- config = function ()
  --   local telescope = require('telescope')
  --   local actions = require("telescope.actions")
  --   telescope.setup{
  --     defaults = {
  --       layout_config = {
  --         width = 0.999999,
  --         height = 0.999999,
  --       },
  --       file_ignore_patterns = {
  --           "^.git/",
  --       },
  --       vimgrep_arguments = {
  --           "rg",
  --           "--color=never",
  --           "--no-heading",
  --           "--with-filename",
  --           "--line-number",
  --           "--column",
  --           "--smart-case",
  --           "--hidden",
  --           "-uu",
  --       },
  --       -- Default configuration for telescope goes here:
  --       -- config_key = value,
  --       mappings = {
  --         i = {
  --           -- map actions.which_key to <C-h> (default: <C-/>)
  --           -- actions.which_key shows the mappings for your picker,
  --           -- e.g. git_{create, delete, ...}_branch for the git_branches picker
  --           ["<C-h>"] = "which_key",
  --         },
  --         n = {
  --           ["q"] = actions.close,
  --         },
  --       }
  --     },
  --     pickers = {
  --       -- Default configuration for builtin pickers goes here:
  --       -- picker_name = {
  --       --   picker_config_key = value,
  --       --   ...
  --       -- }
  --       -- Now the picker_config_key will be applied every time you call this
  --       -- builtin picker
  --     },
  --     extensions = {
  --       fzf = {
  --           fuzzy = true,
  --           override_generic_sorter = true,
  --           override_file_sorter = true,
  --           case_mode = "smart_case",
  --       },
  --       file_browser = {
  --         -- disables netrw and use telescope-file-browser in its place
  --         hijack_netrw = true,
  --         mappings = {
  --           ["i"] = {
  --             -- your custom insert mode mappings
  --           },
  --           ["n"] = {
  --             -- your custom normal mode mappings
  --           },
  --         },
  --     },
  -- },
  --   }
  --   local builtin = require('telescope.builtin')
  --   local opts = { noremap = true }
  --   vim.keymap.set('n', 'sf', "<Cmd>Telescope file_browser path=%:p:h select_buffer=true<CR>", opts)
  --   vim.keymap.set('n', 'sF', builtin.find_files, opts)
  --   vim.keymap.set('n', 'sm', builtin.oldfiles, opts)
  --   vim.keymap.set('n', 'sg', builtin.live_grep, opts)
  --   vim.keymap.set('n', 'sG', builtin.grep_string, opts)
  --   vim.keymap.set('n', 'sb', builtin.buffers, opts)
  --   vim.keymap.set('n', 'sh', builtin.help_tags, opts)
  --   vim.keymap.set('n', 'sq', builtin.quickfix, opts)
  --   vim.keymap.set('n', 'sC', builtin.colorscheme, opts)
  --
  --   vim.keymap.set('n', 'sq', builtin.diagnostics, opts)
  --   vim.keymap.set('n', 'sd', builtin.lsp_workspace_symbols, opts)
  --   vim.keymap.set('n', 'sD', builtin.lsp_document_symbols, opts)
  -- end,
  }
