[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['neosnippet.vim']
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_start_length = 1
let g:deoplete#enable_debug = 1
let g:deoplete#enable_smart_case = 1
autocmd CompleteDone * pclose!
" let g:deoplete#enable_profile = 1
" let g:deoplete#enable_debug = 1
" call deoplete#enable_logging('DEBUG', 'deoplete.log')
set completeopt+=noselect
let g:deoplete#omni#input_patterns = {}
call deoplete#custom#option('omni_patterns', {
  \ 'scala': ['[^.\s*\t]\.\w*', '[:\[,] ?\w*','^import .*', '[^.\s*\t]override def ']
  \})
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i = 1
on_ft = 'snippet'
hook_source = '''
  imap <C-k>     <Plug>(neosnippet_expand_or_jump)
  smap <C-k>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>     <Plug>(neosnippet_expand_target)
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)"
  \: "\<TAB>"

" For snippet_complete marker.
if has('conceal')
  set conceallevel=2 concealcursor=i
endif

  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#enable_completed_snippet = 1
  let g:neosnippet#expand_word_boundary = 1
  let g:neosnippet#snippets_directory = '~/.config/nvim/snippets,' . dein#get('neosnippet-snippets').path . '/neosnippets'
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
epends = 'neomru.vim'
on_source = 'denite.nvim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'eagletmt/neco-ghc'

[[plugins]]
repo = 'jodosha/vim-godebug'
on_ft = 'go'
hook_source = '''
 let g:go_term_enabled=1
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
  let g:go_version_warning = 0
  let g:go_doc_keywordprg_enabled = 0
  let g:go_def_mapping_enabled = 0
'''

[[plugins]]
on_ft = 'typescript'
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
on_ft = 'typescript'
repo = 'jason0x43/vim-js-indent'

[[plugins]]
on_ft = 'typescript'
repo = 'mhartington/nvim-typescript'
build = './install.sh'

[[plugins]]
on_ft = 'swift'
repo = 'landaire/deoplete-swift'
